version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - C:\casalinda\datos:/data/db

  flask:
    build:
      context: C:\Users\Maxi\Desktop\casalinda\Servidor
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pedidos

  angular:
    build:
      context: C:\Users\Maxi\Desktop\casalinda\generarPedido
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    depends_on:
      - flask
  backup:
    build:
      context: C:\Users\Maxi\Desktop\casalinda\buckup
      dockerfile: Dockerfile
    container_name: backup_mongodb
    volumes:
      - C:\casalinda\buckup\data:/backup
    depends_on:
      - mongodb
  #restore:
    #image: mongo:latest
    #container_name: restore_mongodb
    #command: sh -c "mongorestore --host mongodb --drop /backup/2024-05-23-14-35"
    #volumes:
      #- ./backup:/backup
    #depends_on:
      #- mongodb
volumes:
  mongo-data:
  
